### ISSUE TITLE
How can I help? (:

### ISSUE THREAD

**Issue by BroderPeters** [WeAreFairphone/android_device_fairphone_FP4#1]
I'm receiving my Fairphone 4 tomorrow and definitely want to get started with Lineage on it.
Therefore, I would really like to help to get an official build live and running, as also stated here last week: https://forum.fairphone.com/t/fp4-and-lineageos/77347/29?u=broderpeters

I most certainly don't ask for specific instructions or guidance from scratch, but maybe I can help somehow if there are already plans.

**Comment by dk1978** [comment]
Hi, we are just starting out. Once kernel and device tree are ready, feel free to test the build yourself and give feedback.

**Comment by aanze** [comment]
I built and flashed a version that is working without any noticable issue.

Steps I followed were mostly the same as FP3 procedure except:
1. Had to create the roomservice.xml as follows:
`<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote name="device" fetch="https://github.com" revision="lineage-18.1" />
  <remote name="kernel" fetch="https://github.com" revision="lineage-18.1" />
  <project path="device/fairphone/FP4" name="WeAreFairphone/android_device_fairphone_FP4" remote="device" />
  <project path="kernel/fairphone/sm7225" remote="kernel" name="WeAreFairphone/android_kernel_fairphone_sm7225" />
</manifest> `

2. Had to use a iodé build to extract the missing proprietary blobs as most of them wouldn't come with /extract-files.sh 
You will get some warnings, but overall it works.

Only issues:
-> I couldn't flash pico gapps, apparently because system partition is too small, that's a shame given there's no smaller package available
-> I think I should have erased metadata partition with fastboot erase metadata command, because I got "E: Couldn't mount /metadata" message during flashing. 
Erasing this partition appears to be part of the procedure of flashing /e/ OS and iodé so I guess it has to be done for some reaason.
This didn't prevent the rom to boot flawlessly anyway.

This was my first ever build so I'm merely a novice, but ready to try and help if my modest skills are of some use.

**Comment by stendarr** [comment]
> feel free to test the build yourself and give feedback.

I've had no problems building it, I even managed to patch it for microG. Been running it for 2 or 3 days now without any problems. The only issue I saw is that the camera only uses 12 megapixels instead of 48, which makes the photos look worse. Also the wide-angle lens is neither usable nor detected, in OpenCamera as well.

Is there a guide on how to systematically test LineageOS or some sort of overview on things that usually fail or don't work properly? That way I could quickly test and give feedback on the things that matter most.

**Comment by phikal** [comment]
I would like to test and contribute if possible, but I've been stuggling to build the Lineage from source.  Could a few comments specifically for the FP4 be added to the README to make this easier?

**Comment by BroderPeters** [comment]
> I would like to test and contribute if possible, but I've been stuggling to build the Lineage from source. Could a few comments specifically for the FP4 be added to the README to make this easier?

@phikal I would recommend checking out this forum thread for building (:
https://forum.fairphone.com/t/fp4-and-lineageos/77347

**Comment by phikal** [comment]
Broder Peters ***@***.***> writes:

>> I would like to test and contribute if possible, but I've been
> stuggling to build the Lineage from source. Could a few comments
> specifically for the FP4 be added to the README to make this easier?
>
> @phikal I would recommend checking out this forum thread for building (:
> https://forum.fairphone.com/t/fp4-and-lineageos/77347

That is the thread where I came from, but the advice given in that
thread didn't help.

I honestly think that having some basic advice in the repository (be in
in the README or some other conventional place) would help newcomers
like me a lot.  I am interested in having a stable and official Lineage
image as soon as possible and am willing to help get there, but the
instructions are sporadic, inconsistent and lack details/advice
concerning common mistakes.
